stages:
  preprocess:
    cmd: python src/preprocess.py data/raw.csv data/processed.csv
    deps:
      - src/preprocess.py
      - data/raw.csv
    outs:
      - data/processed.csv

  train:
    cmd: python src/train.py data/processed.csv models/
    deps:
      - src/train.py
      - data/processed.csv
    
